### ISSUE TITLE
Command only channel and delete non commands in that channel

### ISSUE THREAD

**Issue by Starga123** [malouro/ggis-bot#84]
**Is your feature request related to an existing command or feature?**
Yes, it's related to the !lfg command.

**Describe the solution you'd like**
To set an LFG channel for the command to be used in, such as `!settings lfg lfgchannel #lfg` and another command such as `!settings lfg commandonly true` to only allow commands in that channel, can be turned off.

**Additional context**
Spoke to you via Discord about this so a lot of the information is there

**Comment by malouro** [comment]
I think it'd be useful in general to have channels as a `type` in `!settings`, that way people can make settings that expect channels as inputs. Then we can leverage that to make certain channels for commands only

**Comment by malouro** [comment]
Made the ability to have text channels and users as `types` in `!settings` in #85 

gonna take a look at this as a bot setting
